src_imgs: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/010_Dima_16_01_25_TK_podmoskovie/005_verified_annotation/003_Gelya_28_01_25_IMG_3255/recived/selected_labels/images"
src_labels: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/010_Dima_16_01_25_TK_podmoskovie/005_verified_annotation/003_Gelya_28_01_25_IMG_3255/recived/selected_labels/labels"
dst_imgs: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/010_Dima_16_01_25_TK_podmoskovie/005_verified_annotation/003_Gelya_28_01_25_IMG_3255/recived/selected_labels/visulize"

# classes:
#   - "000_target_top"
#   - "001_background_top"
#   # - "002_strip"
#   # - "003_coil"
  # - "004_ERROR_unknown"

classes:
  - "000_target_top"
  - "001_backround_top"
  - "002_strip"
  - "003_coil"
  # - "004_ERROR_unknown"

# previous classes
# classes:
#   - "000_coil"
#   - "001_top_backround"
#   - "002_top_target"
#   - "003_strip"

colors:
  - [0, 0, 255] # red
  - [171, 0, 111] # green_white
  - [255, 0, 18 ] # dark blue
  - [236, 255, 1] # green_white
  # - [0, 255, 255] # yellow

# Настройки отображения (опциональные)
box_thickness: 4     # толщина рамок
font_scale: 1     # размер шрифта
font_thickness: 2    # толщина шрифта

