src_imgs: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/images"
src_labels: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/labels"
dst_imgs: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/plotted"

# classes:
#   - "000_target_top"
#   - "001_background_top"
#   # - "002_strip"
#   # - "003_coil"
  # - "004_ERROR_unknown"

classes:
  - "fully-ripe"
  - "semi-ripe"
  - "unripe"
  # - "003_coil"
  # - "004_loose_strip"

# previous classes
# classes:
#   - "000_coil"
#   - "001_top_backround"
#   - "002_top_target"
#   - "003_strip"

colors:
  - [0, 0, 255] 
  - [255, 0, 18 ]  
  - [0, 255, 255]
  # - [236, 255, 1] 
  # - [ 171, 0, 111]
# Настройки отображения (опциональные)
box_thickness: 4     # толщина рамок
font_scale: 1     # размер шрифта
font_thickness: 2    # толщина шрифта

