src_imgs: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/011_ECO_C_january_2025/005_verified_annotation/001_labeled_03_02_25/recived/IMG_1388_Gelya/project-21-at-2025-02-04-16-35-8de69fda/images"
src_labels: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/011_ECO_C_january_2025/005_verified_annotation/001_labeled_03_02_25/recived/IMG_1388_Gelya/project-21-at-2025-02-04-16-35-8de69fda/labels"
dst_imgs: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/011_ECO_C_january_2025/005_verified_annotation/001_labeled_03_02_25/recived/IMG_1388_Gelya/visualize"

# classes:
#   - "000_target_top"
#   - "001_background_top"
#   # - "002_strip"
#   # - "003_coil"
  # - "004_ERROR_unknown"

classes:
  - "000_target_top"
  - "001_backround_top"
  - "002_strip"
  - "003_coil"
  # - "004_ERROR_unknown"

# previous classes
# classes:
#   - "000_coil"
#   - "001_top_backround"
#   - "002_top_target"
#   - "003_strip"

colors:
  - [0, 0, 255] # red
  - [171, 0, 111] # green_white
  - [255, 0, 18 ] # dark blue
  - [236, 255, 1] # green_white
  # - [0, 255, 255] # yellow

# Настройки отображения (опциональные)
box_thickness: 4     # толщина рамок
font_scale: 1     # размер шрифта
font_thickness: 2    # толщина шрифта

