
# Путь к исходным данным, папкам с источниками
path_data: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/001_leaves_diseases/002_quality_classifier/001_raw_data"
# Путь к файлу с итоговыми данными 
path_final_data: "path_final_data.txt"


# Путь для сохранения excel файла
path_out_excel: /Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/001_leaves_diseases/002_quality_classifier/002_train_data/008_train_set
# Имя директории для сохранения excel файла
name_excel_file: all_sources_data.csv


# Список классов types =  [int, str]
classes: [1, 2, 3, 4, 5, 6, 7]




