
# Путь к исходным данным, папкам с источниками
path_data: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/002_train_data/003_train_25_02_25/data_folders/train"
# Путь к файлу с итоговыми данными
path_final_data: "path_final_data.txt"


# Путь для сохранения train set
path_out: /Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/002_train_data/003_train_25_02_25/001_data
# Имя директории для сохранения train или set
name_dir: train



### Validation
# Список источников - name folders
# list_sources:
#   - 003_001_Dim_Yar_Part3

list_sources:
  - 003_001_Dim_Yar_001
  - 003_001_Dim_Yar_Part1
  - 003_001_Dim_Yar_Part2
  - 003_002_Kaagle_Ripe_Unripe_binary
  - 003_003_datasetninja_tomatOD
  - 003_004_mendeleyData_Immature
  - 003_004_mendeleyData_Mature
  - 003_005_roboflow_3_classes


### Train
# list_sources:
#   - 002_004_ECO_cult_I_Podmoskovie_may_2024
#   - 002_016_AM_from_tg_until_1oct
#   - 002_017_trip_oct_Sosnogorsk
#   - 002_018_photo_panorama_lotok_21right_dhau
#   - 002_019_photo_panorama_lotok_19_dhau
#   - 002_020_photo_sony_Alex
#   - 002_026_Death_leaf_Olga
#   - 002_027_Death_leaf_Gelya
#   - 002_032_logitech_19_lotok
#   - 002_034_ImageNet_val_garbage


# Суммарное количество изображений в классе по всем источникам, папкам
amount_in_class: 1200

# Список классов types =  [int, str]
classes: ["1", "2", "3", "4", "5", "6"]
# classes: ["1", "2", "3", "4", "5", "6", "13_rotten", "14_garbage", "15_many"]
# classes: [1, 2, 3, 4, 5, 6, 7]




