path_labels: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/002_train_data/006_train_set/data/val/labels"

classes:
  - "000_target_top"
  - "001_backround_top"
  - "002_strip"
  - "003_coil"
  - "004_loose_strip"