# Configuration for JSON File Renamer

# Source directory containing files with names like IMG_1232.jpg.json
src: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_007_datasetninja_LaboroTomato/002_raw_data_img/data_ninja/Train/ann"

# Destination directory where renamed files (IMG_1232.json) will be saved
dst: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_007_datasetninja_LaboroTomato/002_raw_data_img/data_ninja/Train/ann_right_name"