path_in: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/002_train_data/001_data/train"
path_out: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/002_train_data/001_data/val"
transfer_percentage: 0.08