path_in: "/home/yaroslav/Documents/001_Projects/005_car_number/data/001_raw_data/001_plates/008_gorniy102"
path_out: "/home/yaroslav/Documents/001_Projects/005_car_number/data/001_raw_data/001_plates/009_gorniy102Val"
transfer_percentage: 0.06