# Configuration for YOLO Segmentation Visualizer

# Directory containing original images
src_imgs: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/001_разметка_здоровый класс/001_здоровый класс_17042025_Гелия/project-39-at-2025-04-17-17-37-125bfa83/images"

# Directory containing YOLO segmentation labels (.txt files)
src_labels: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/001_разметка_здоровый класс/001_здоровый класс_17042025_Гелия/project-39-at-2025-04-17-17-37-125bfa83/labels"

# Path to classes.txt file
classes_txt: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/001_разметка_здоровый класс/001_здоровый класс_17042025_Гелия/project-39-at-2025-04-17-17-37-125bfa83/classes.txt"

# Directory where visualized images will be saved
dst_plotted: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/001_разметка_здоровый класс/001_здоровый класс_17042025_Гелия/project-39-at-2025-04-17-17-37-125bfa83/plotted"

# Optional parameters
# visualization:
#   alpha: 0.4  # Transparency of segmentation masks (0-1)
#   linewidth: 1.5  # Width of segmentation outlines
#   dpi: 200  # Resolution of output images