# Configuration for YOLO Segmentation Visualizer

# Directory containing original images
src_imgs: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/images"

# Directory containing YOLO segmentation labels (.txt files)
src_labels: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/labels"

# Path to classes.txt file
classes_txt: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/classes.txt"

# Directory where visualized images will be saved
dst_plotted: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/plotted"

# Optional parameters
# visualization:
#   alpha: 0.4  # Transparency of segmentation masks (0-1)
#   linewidth: 1.5  # Width of segmentation outlines
#   dpi: 200  # Resolution of output images