# Configuration for YOLO Segmentation Visualizer

# Directory containing original images
src_imgs: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_013_AM_from_tg/005_verified_annotation/001_GelOlg/recived/Olga/project-3-at-2025-03-24-16-20-dc9c43dc/images"

# Directory containing YOLO segmentation labels (.txt files)
src_labels: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_013_AM_from_tg/005_verified_annotation/001_GelOlg/recived/Olga/project-3-at-2025-03-24-16-20-dc9c43dc/labels"

# Path to classes.txt file
classes_txt: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_013_AM_from_tg/005_verified_annotation/001_GelOlg/recived/Olga/project-3-at-2025-03-24-16-20-dc9c43dc/classes.txt"

# Directory where visualized images will be saved
dst_plotted: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_013_AM_from_tg/005_verified_annotation/001_GelOlg/recived/Olga/project-3-at-2025-03-24-16-20-dc9c43dc/plotted"

# Optional parameters
# visualization:
#   alpha: 0.4  # Transparency of segmentation masks (0-1)
#   linewidth: 1.5  # Width of segmentation outlines
#   dpi: 200  # Resolution of output images