# Configuration for JSON to YOLO Segmentation Converter

# Directory containing JSON files to be converted
src_json: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/labels"

# Directory where YOLO format files will be saved
out_path: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/003_tomatos/003_tomatoes_ripeness_stage/001_raw_data/003_003_datasetninja_tomatOD/002_raw_data_img/tomatod_yolo/train/renamed"

# Optional parameters can be added here as needed
# verbose: true
# skip_existing: false