src_annot_dir: "/fanxiangssd/yaroslav/projects/004_sk10/data/data/001_raw_data/001_001_SH17_kaagle/005_verified_annotation/004_hypothesis/data/labels"
dst_annot_dir: "/fanxiangssd/yaroslav/projects/004_sk10/data/data/001_raw_data/001_001_SH17_kaagle/005_verified_annotation/001_hypothesis/labels"
dst_classes:   "/fanxiangssd/yaroslav/projects/004_sk10/data/data/001_raw_data/001_001_SH17_kaagle/005_verified_annotation/001_hypothesis/classes.txt"


as_is_classes:
    - 01_Person
    - 02_Head
    - 03_Face
    - 04_Helmet


remap:
    01_Person: 01_Person


order_new_classes:
    - 01_Person
