input:
  src: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/010_Dima_16_01_25_TK_podmoskovie/001_raw_vids/tops_15_01_25"  # путь к видео файлам
  dst: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/010_Dima_16_01_25_TK_podmoskovie/002_raw_data_img/out"  # путь для сохранения кадров
  rate: 5           # частота захвата кадров

video_formats:        # поддерживаемые форматы видео
  - ".mp4"
  - ".avi"
  - ".MOV"
  - ".asf"