input:
  src: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/011_ECO_C_january_2025/001_raw_vids/"  # путь к видео файлам
  dst: "/Volumes/Orico/projetcs_sbs/001_green-houses/001_DS_models/002_tops/001_tops_detection/001_raw_data/011_ECO_C_january_2025/002_raw_data_img/out_freq5/"  # путь для сохранения кадров
  rate: 5           # частота захвата кадров

video_formats:        # поддерживаемые форматы видео
  - ".mp4"
  - ".avi"
  - ".MOV"
  - ".asf"