# Configuration for combined YOLO segmentation visualization
# Directory containing original images
src_imgs: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/002_разметка_здоровый_механика/001_здоровый_механика_21042025_Гелия/project-38-at-2025-04-21-13-37-f6967055/images"

# Directory containing YOLO segmentation labels (.txt files)
src_labels: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/002_разметка_здоровый_механика/001_здоровый_механика_21042025_Гелия/project-38-at-2025-04-21-13-37-f6967055/labels"

# Path to classes.txt file
classes_txt: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/002_разметка_здоровый_механика/001_здоровый_механика_21042025_Гелия/project-38-at-2025-04-21-13-37-f6967055/classes.txt"

# Directory where visualized images with segmentation will be saved
dst_plotted: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/002_разметка_здоровый_механика/001_здоровый_механика_21042025_Гелия/project-38-at-2025-04-21-13-37-f6967055/plotted"

# Directory where combined images (original + segmentation side by side) will be saved
combined: "/Volumes/T7_Shiled/green/001_data_green/001_leaves/004_definite_seg/001_raw_data/004_022_photo_iphone_Yaroslav/006_labeling/результат разметки/002_разметка_здоровый_механика/001_здоровый_механика_21042025_Гелия/project-38-at-2025-04-21-13-37-f6967055/combined"


# Optional parameters can be added here if needed in the future:
# visualization:
#   alpha: 0.4  # Transparency of segmentation masks (0-1)
#   linewidth: 1.5  # Width of segmentation outlines
#   dpi: 200  # Resolution of output images